# Lecture 8 - NumPy

In this, and the coming lectures, we will be learning different **external libraries**. The lectures will also include links to **documentation** of those libraries, and you will be expected to get comfortable with using documentation.

[**NumPy**](https://numpy.org/doc/stable/) stands for "numerical python" and provides an efficient implementation of large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

As Data Scientists, you will employ these to analyse and summarise datasets (which will be the focus of this week's workshop).

We will cover the following functionality of the NumPy library in today's lecture:
- [NumPy arrays](#NumPy-arrays)
    - [Array dimensions](#Array-dimensions)
    - [Creating NumPy arrays](#Creating-NumPy-arrays)
    - [Indexing NumPy arrays](#Indexing-NumPy-arrays)
    - [Combining NumPy arrays](#Combining-NumPy-arrays)
- [Operations with arrays](#Operations-with-arrays)
    - [Operations between arrays and numbers](#Operations-between-arrays-and-numbers)
    - [Operations between arrays and arrays](#Operations-between-arrays-and-arrays)
- [Analysing data](#Analysing-data)
- [Basic linear algebra (extension)](#Basic-linear-algebra-(extension))
    - [System of linear equations (extension)](#System-of-linear-equations)
    
_Note: You need to run every cell in this notebook to ensure the later cells run correctly. Skipping some cells might result in run-time errors in other cells._

NumPy is an **external library**. This means you need to `import` the `numpy` module into your code to use the functionality it provides. This is typically done with:

In [5]:
import numpy as np

Any other alias other than `np` can be used, by `np` is standard.

## NumPy arrays

Central to NumPy is the _array_ class (specifically, [`numpy.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)). It provides the functionality to manipulate [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) objects. [_Arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) are similar to _lists_ in Python (they are **ordered**, **changeable**, and **allow duplicates**), but NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) usually contain elements of the **same data type** (typically numbers).

NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) can be created from Python lists with [`numpy.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html):

```python

array_var = np.array(list_var)
```
where `array_var` is the variable holding the NumPy [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), and `list_var` is the python list.

_Note: This is a simplified example of use, follow the documentation link to see the full function signature._

##### Example

Let's show creating several different python lists, and creating NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) from them:
- 5 floating point numbers:

In [6]:
flist = [0.5, 1.6, 2.7, 3.8, 9.1]

print(type(flist[0]), type(flist[-1]))

# create a NumPy array from Python list:
farray = np.array(flist)

print(type(farray[0]), type(farray[-1]))

print(flist)
print(farray)
print(type(farray), type(flist))

<class 'float'> <class 'float'>
<class 'numpy.float64'> <class 'numpy.float64'>
[0.5, 1.6, 2.7, 3.8, 9.1]
[0.5 1.6 2.7 3.8 9.1]
<class 'numpy.ndarray'> <class 'list'>


- a nested list, containing 3 lists of 3 integers each:

In [7]:
nlist = [[5, 1, 3],
         [2, 7, 1],
         [8, 1, 0]]
narray = np.array(nlist)
print(nlist)
print(narray)

[[5, 1, 3], [2, 7, 1], [8, 1, 0]]
[[5 1 3]
 [2 7 1]
 [8 1 0]]


- all numbers between 500 and 1500:

In [8]:
llist = range(500, 1500, 50)  
larray = np.array(llist)
print(llist)
print(larray)

range(500, 1500, 50)
[ 500  550  600  650  700  750  800  850  900  950 1000 1050 1100 1150
 1200 1250 1300 1350 1400 1450]


- additional examples to show in the lecture:

### Array dimensions

Python lists can be nested, but are most often not. Typically, they just _list_ a sequence of elements -- they are **one dimensional (1D)**.

NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) can also be 1D, but their power lies in handling 2D and multi-dimensional (nD) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). This can be used to represent:
- mathematical functions
- tabular data
- images
- ...

With python lists, to get the number of elements in a list, you can write:
```python
length = len(mylist)
```

However, this would just give you a number of "top level" elements. For a nested list:

In [9]:
# create a nested list
list_nested = [[5, 1, 0, 2, 1],
               [2, 7, 1, 2, 0],
               [8, 1, 2, 2, 1],
               [3, 1, 0, 1, 2]]

# get the number of elements in the list
print(len(list_nested))
# get the length of the first element - which is also a list
print(len(list_nested[1]))

4
5


With NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), you can use the [`numpy.ndarray.shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) attribute to find out the size of every [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) dimension (called  **axis** in NumPy) as a _tuple_:

(_Reminder:_ Tuples are Python objects that are ordered, _unchangeable_, and allow duplicates.)

In [10]:
# create a numpy array from the nested list in the previous example
array_2d = np.array(list_nested)
# print the array
print(array_2d)
# get the length of the array - the number of rows
print(len(array_2d))
# get the shape of the array - both the number of rows and columns
print(array_2d.shape)
# the total number of elements of the array can be obtained by multiplying all elements of the shape
print(array_2d.shape[0]*array_2d.shape[1])

[[5 1 0 2 1]
 [2 7 1 2 0]
 [8 1 2 2 1]
 [3 1 0 1 2]]
4
(4, 5)
20


##### Example

For the nested Python list given below, and the constructed 2D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), let us retrieve the size of the second dimension/axis ("how many columns are there?") using:
- the list `list_nested`
- the array `array2d`

In [11]:
# create a nested list
list_nested = [[4, 2, 8, 1],
               [3, 4, 2, 7],
               [9, 2, 1, 4],
               [1, 6, 3, 3],
               [8, 5, 1, 7],
               [9, 6, 1, 2]]
# create a numpy array from the list
array_2d = np.array(list_nested)

# to get the number of elements in a nested list, we must index one of the elements first
print(len(list_nested[-1]))

# to get the number of columns in a numpy array, we can read the second element of shape:
print(array_2d.shape[1])


4
4


### Creating NumPy arrays

You have seen NumPy [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) initialised from lists.
```python

array_var = np.array(list_var)
```

Now, let's look at some other ways of creating NumPy arrays.

#### 1D arrays

To create 1D [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) with regularly spaced elements, you can use [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) or [`numpy.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace).

The syntax of [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) is similar to the python function `range`:
> `numpy.arange([start, ]stop, [step])`
>
> Returns an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of evenly spaced elements between `start` and `stop` where `step` is the difference between consecutive elements. By default, `start=0` and `step=1`. `stop` is not included.

However, [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) can use floating-point numbers, while python's `range()` function can not.

_Note: this is a simplified function signature, follow the documentation link to see the full function signature._

##### Example

Let's create some NumPy arrays with [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) and compare them to arrays created from python lists initialised with `range()`:
- all numbers between 0 and 10:

In [13]:
print(np.arange(10))

print(np.array(range(10)))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


- all even numbers between 10 and 20:

In [14]:
print(np.arange(5, 15))
print(np.array(range(5, 15)))

[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]


And here is an an example of using [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) which can not be emulated with `range()`.

In [12]:
print(np.arange(2, 1, -0.1))

[2.  1.9 1.8 1.7 1.6 1.5 1.4 1.3 1.2 1.1]


Instead of specifying the step, [`numpy.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) allows you to specify the number of elements between the first and the last:
> `numpy.linspace(start, stop, num=50, endpoint=True)`
>
> Returns an array of `num` evenly spaced elements between `start` and `stop`. If `endpoint=True` (default), `stop` is included in the array, otherwise it is not.

_Note: this is a simplified function signature, follow the documentation link to see the full function signature._

##### Example

Creating different NumPy arrays with [`numpy.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace).
- 10 evenly spaced numbers between 1 and 10:

In [29]:
print(np.linspace(1, 10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


- careful, requesting _20_ evenly spaced numbers between 1 and 10 might not have the expected result:

In [16]:
print(np.linspace(1, 10, 20))

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


- you can take this into account by asking for 19 numbers:

In [17]:
print(np.linspace(1, 10, 19))

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


- you can also specify that the endpoint of the range is not included in the list:

In [23]:
print(np.linspace(0, 10, 20, endpoint=False))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


- using [`numpy.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) and [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange) can often achieve the same result (but remember, arange never includes the end point):

In [27]:
print(np.linspace(0, 1, 11))
print(np.arange(0, 1.1, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- another example of the same output achieved with [`numpy.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) and [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange):

In [28]:
print(np.linspace(0, 1, 10, endpoint=False))
print(np.arange(0, 1, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 2D and nD arrays

To create [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of any shape containing all zeros, we can use [`numpy.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html). Similarly, to create an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of any shape filled with ones, use [`numpy.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html).

> `numpy.zeros(shape)`
>
> `numpy.ones(shape)`
>
> Returns a new [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) filled with zeros/ones, of the given shape. Shape can be an int, or a tuple of ints.

_Note: this is a simplified function signature, follow the documentation link to see the full function signature._

Other similar functions worth checking out are [`numpy.empty()`](https://numpy.org/doc/stable/reference/generated/numpy.empty.html) and [`numpy.full()`](https://numpy.org/doc/stable/reference/generated/numpy.full.html).

##### Example

We create:
 - a 1D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of length 3 filled with zeros

In [32]:
print(np.zeros(3))

[0. 0. 0.]


 - a 1D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of length 2 filled with ones

In [30]:
print(np.ones(2))

[1. 1.]


 - a 2D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of dimensions $3\times2$ filled with zeros

In [31]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


 - a 3D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of dimensions $2\times2\times2$ (think of it as a cube) filled with ones

In [34]:
print(np.ones((2,2,2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


We can also create an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) filled with _random numbers_ from the $[0.0, 1.0)$ interval using [`numpy.random.random_sample()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random_sample.html). This function can also be used to get a random scalar (a single number).

> `random.random_sample(shape=None)`
>
>  Returns an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) initialised with random numbers from $[0.0, 1.0)$ interval of the shape `shape`. If `shape` is `None`, returns a random scalar.

##### Example

How can we use `numpy.random.random_sample()` to create:
- a $3\times2$ [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) with random numbers from the $[0.0, 1.0)$ interval

In [36]:
print(np.random.random_sample((3, 2)))

[[0.4231998  0.1546934 ]
 [0.89591609 0.78740149]
 [0.54411568 0.27327126]]


- a single random number (scalar) from the $[0.0, 1.0)$ interval

In [37]:
print(np.random.random_sample())

0.7509422736423254


- a single random number from the $[5.0, 10.0)$ interval

In [39]:
# [0, 1) (*5)--> [0, 5) (+5)--> [5, 10)
print(np.random.random_sample()*5 + 5)

7.178708862271536


### Indexing NumPy arrays

#### 1D arrays

**For 1D [arrays](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), indexing works the same as with python lists**. Let's show some of this functionality that works on both python lists and [**NumPy**](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

##### Example
We will create a python list `flist`, and a corresponding [**NumPy**](https://numpy.org/doc/stable/) [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) `farray`, to showcase some of this functionality:

In [44]:
flist = [0.5, 1.6, 2.7, 3.8, 9.1]
farray = np.array(flist)

- accessing a single element:

In [43]:
print(flist[3], farray[3])

3.8 3.8


- accessing an element by relative indexing from the last element

In [41]:
print(flist[-2], farray[-2])

3.8 3.8


- slicing

In [42]:
print(flist[1:3], farray[1:3])

[1.6, 2.7] [1.6 2.7]


- combination of the above

In [46]:
# slicing with back indexing
print(flist[2:-1], farray[2:-1])

# slicing with a step of 2 (skip every 2nd element)
print(flist[1::2], farray[1::2])

[2.7, 3.8] [2.7 3.8]
[1.6, 3.8] [1.6 3.8]


#### 2D and nD arrays

However, **2D (or nD) [**NumPy**](https://numpy.org/doc/stable/) [arrays](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) are indexed with comma separated arguments in the same square brackets**, while with a Python list, every argument goes into a separate bracket.

This is because if `l` is a nested list (list of lists), then e.g. `l[3]` is a (non-nested) list. However, 1 2D [**NumPy**](https://numpy.org/doc/stable/) [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) is single object, not a composite one, so both dimensions are indexed jointly.

##### Example

In [47]:
# create a nested list and a corresponding numpy array
list_nested = [[5, 1, 3],
               [2, 7, 1],
               [8, 1, 0],
               [1, 5, 2]]
array_2d = np.array(list_nested)

# to access elements from a nested list,
# you first index the row ("which sub-list?")
# and then the column ("which element of the sub-list")
# in separate square brackets [] :
print(list_nested[1][2])

# to access elements from a numpy array,
# you index the row and column in the same
# square brackets:
print(array_2d[1,2])

1
1


**[NumPy](https://numpy.org/doc/stable/) supports partial indexing** (e.g. specifying just the first dimension -- selecting only a single row from a 2D array) with the same syntax as with Python lists:

In [48]:
print(list_nested[1])
print(array_2d[1])

[2, 7, 1]
[2 7 1]


However, in [NumPy](https://numpy.org/doc/stable/) we can also select a **single column**, or only **some columns**. A similar syntax gives unexpected results when applied directly to Python lists (you can't chain list slicing on Python lists).

##### Example
In this example, we first show how you can index the columns of [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), while a similar approach won't work for python lists (check the comments for a detailed explanation of why this syntax fails for python lists):

In [49]:
# create a nested list and a corresponding array
list_nested = [[5, 1, 3],
               [2, 7, 1],
               [8, 1, 0],
               [1, 5, 2]]
array_2d = np.array(list_nested)

# You can easily index a column of a numpy array (middle column - index 1):
print("Select the middle column only (correct, NumPy array):", array_2d[:, 1])

# However, a similar approach won't work for python lists.
# A similar syntax on python lists actually first parses list_nested[:],
# which just selects the whole list and is equal to list_nested
# Then, it indexed the element at position 1 (0-indexed) from list_nested[:] (which is just list_nested)
# So finally, list_nested[:][1] is same as list_nested[1], the first row, not column
print("Select the middle column only (incorrect, Python list):", list_nested[:][1])


Select the middle column only (correct, NumPy array): [1 7 1 5]
Select the middle column only (incorrect, Python list): [2, 7, 1]


Similarly, you can also perform splicing on both the rows and columns of a [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), while a similar syntax wouldn't work for python lists:

In [50]:
# Performing slicing on both rows and columns on a numpy array
print("Last two columns from first two rows (correct, Numpy array):\n", array_2d[:2, -2:])

# A similar approach doesn't work for python lists.
# With python lists, list_nested[:2] selects the first two elements=rows, so is equal to [[5, 1, 3],[2, 7, 1]]
# Then, list_nested[:2][-2:] selects the last two elements of the above list (which only has two elements)
print("Last two columns from first two rows (incorrect, Python list):\n", list_nested[:2][-2:])

Last two columns from first two rows (correct, Numpy array):
 [[1 3]
 [7 1]]
Last two columns from first two rows (incorrect, Python list):
 [[5, 1, 3], [2, 7, 1]]


We can also select only specific columns or rows within a [NumPy](https://numpy.org/doc/stable/) [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

##### Example
Select the first and third column.

In [57]:
print(array_2d[:, [0,2]])

[[5 3]
 [2 1]
 [8 0]
 [1 2]]


##### Example

This can be used to re-order the rows or columns of an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). Re-arrangeing the `array_2d` to:
- change the row order (0-indexed) from $0, 1, 2, 3$ to $2, 3, 0, 1$

In [53]:
list_nested = [[5, 1, 3],
               [2, 7, 1],
               [8, 1, 0],
               [1, 5, 2]]   
array_2d = np.array(list_nested)
#print(array_2d)
print(array_2d[[2, 3, 0, 1]])

[[8 1 0]
 [1 5 2]
 [5 1 3]
 [2 7 1]]


- change the column-order (0-indexed) from $0, 1, 2$ to $1, 2, 0$

In [54]:
print(array_2d[:, [1, 2, 0]])

[[1 3 5]
 [7 1 2]
 [1 0 8]
 [5 2 1]]


We can also index [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) using a list of _boolean_ values (of the same length as the corresponding dimension/axis of the array). This list of _boolean_ values is often referred to as a **mask**, instructing [NumPy](https://numpy.org/doc/stable/) which rows/columns to index and which not to.

##### Example
This can also be used to select only certain columns from an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). Selecting only:
- rows (0-indexed) $0, 2$:

In [58]:
# with boolean values
print(array_2d[[True, False, True, False]])

# remember, we can achieve a similar thing directly indexing rows 0 and 2:
print(array_2d[[0,2]])

[[5 1 3]
 [8 1 0]]
[[5 1 3]
 [8 1 0]]


- columns $0, 1$:

In [59]:
# with boolean values
print(array_2d[:, [True, True, False]])

# or directly indexing columns
print(array_2d[:, [0, 1]])

[[5 1]
 [2 7]
 [8 1]
 [1 5]]
[[5 1]
 [2 7]
 [8 1]
 [1 5]]


#### Mask indexing

However, indexing [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) using _boolean lists_ is very powerful, if you think of them as **masks**. This is because it is possible to **construct masks based on logical operators**, which are calculated on our original [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). 

For example, we create an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) containing 100 random numbers between $0$ and $1$, and then select only the elements which are greater than a certain value, e.g. $0.5$:

In [61]:
# create an array containing 100 random numbers between 0 and 1
many_numbers = np.random.random_sample(100)
#print(many_numbers)

# determine the mask containing the positions of numbers greater than 0.5
big_number_positions = many_numbers > 0.5

# as we can see, this mask is a boolean array with 100 elements:
print(big_number_positions)

# we can now use this mask to index only the numbers greater than 0.5:
print(many_numbers[big_number_positions])

# you can also do mask indexing directly, without storing the
# mask in a separate variable:
less_numbers = many_numbers[many_numbers > 0.5]
print(less_numbers.shape)

[ True  True False False False  True  True False False False  True False
 False  True False  True  True False False  True  True  True  True  True
 False False False  True False  True  True  True False False False  True
 False  True  True False False  True  True  True  True False  True  True
  True False  True False  True  True False  True False  True  True  True
 False False  True False  True  True  True False False False False  True
 False  True  True  True False  True  True False  True False  True  True
 False  True  True  True False False  True  True  True  True False  True
 False False False False]
[0.55745361 0.58563705 0.80510558 0.5470383  0.97769603 0.63769222
 0.67443581 0.91000532 0.79743828 0.69046491 0.63045057 0.77359459
 0.9676163  0.83451198 0.6509786  0.78357799 0.53471326 0.78783467
 0.60604922 0.66135947 0.91329615 0.56180666 0.63718939 0.52723785
 0.90662316 0.68421641 0.78456469 0.50948199 0.75780893 0.70895903
 0.89417158 0.73317513 0.74225943 0.86538064 0.60082574

In general, comparing a [NumPy](https://numpy.org/doc/stable/) [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) to a number produces a **mask array**.

> A *mask array* is an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) containing only _boolean_ (`True`/`False`) values. 
> It can be used to index any [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of the same shape.

This means we can use a mask [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) to index the original [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) used to create the mask (like above), but also a different [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

##### Example

This example shows:
- creating an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of ordered numbers between 0 and 99 `sequential_numbers`
- creating a mask based on the [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of random numbers from the previous example (`many_numbers`); this [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) will be `True` where the element of `many_numbers` is higher than $0.8$, `False` otherwise
- select all elements of the ordered [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) `sequential_numbers` where the corresponding element of `many_numbers` is larger than $0.8$

In [62]:
sequential_numbers = np.arange(100)
print(sequential_numbers)
mask = many_numbers > 0.8
sequential_numbers[mask]
print(sequential_numbers[mask], sequential_numbers[mask].shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 5 10 16 23 27 41 46 55 59 64 65 66 74 75 82 83 85 86 95] (19,)


A **one-dimensional mask can also be used to index a 2D [array](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)**, and retrieve only rows of interest:

_Note: When working with data, **rows** often correspond to individual samples (e.g. one customer, one product), while the **columns** correspond to measured/monitored characteristics (e.g. age, average monthly spend, price...)._

In [63]:
samples = np.array([[0.5, 10, 1.7],
                    [0.2, 15, 6.3],
                    [0.7, 17, 5.2],
                    [0.1, 12, 2.8],
                    [0.3, 15, 6.8]])
labels = np.array(['A', 'A', 'B', 'B', 'A'])
mask = (labels == 'A')
#mask = [True, True, False, False, True]
#print(mask)
print(samples[mask])

[[ 0.5 10.   1.7]
 [ 0.2 15.   6.3]
 [ 0.3 15.   6.8]]


##### Examples

A more complex example -- selecting all rows where the second column is higher equal to 15:

In [108]:
mask = (samples[:,1] >= 15)
print(samples[mask])

print(samples[samples[:, 1] >= 15])

#print(samples[mask]) # equal to samples[mask, :]

[[ 0.2 15.   6.3]
 [ 0.7 17.   5.2]
 [ 0.3 15.   6.8]]
[[ 0.2 15.   6.3]
 [ 0.7 17.   5.2]
 [ 0.3 15.   6.8]]


Or the reverse: select (all the rows from) all the columns where the third row is higher than 5:

In [112]:
mask = samples[2] > 5
print(samples[:, mask])

print(samples[:, samples[2] > 5])

[[10.   1.7]
 [15.   6.3]
 [17.   5.2]
 [12.   2.8]
 [15.   6.8]]
[[10.   1.7]
 [15.   6.3]
 [17.   5.2]
 [12.   2.8]
 [15.   6.8]]


**Masks can also be combined.** Selecting all rows where the second column is higher than 16 or the first column is higher than 0.4:

In [114]:
mask = (samples[:, 1] > 14) & (samples[:, 0] < 20)


print(samples[mask]) # print(samples[mask])

[[ 0.2 15.   6.3]
 [ 0.7 17.   5.2]
 [ 0.3 15.   6.8]]


All columns where first row is higher than 0.1 and last row is lower than than 10:

In [115]:
mask = (samples[0, :] > 0.1) & (samples[-1, :] < 10)
print(samples[:, mask])

[[0.5 1.7]
 [0.2 6.3]
 [0.7 5.2]
 [0.1 2.8]
 [0.3 6.8]]


### Combining NumPy arrays

We have now shown how to select only parts of [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). How can we join them together?

The function [`numpy.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) can be used to join two or more arrays, along any axis (the first, by default):

> `numpy.concatenate((a1, a2, ...), axis=0)`
>
> Returns a new [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) joining the [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) `a1`, `a2`, ... along `axis`  (first by default).

In [64]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[10, 11, 12],
              [11, 12, 13]])
#print(a)
#print(b)

c = np.concatenate((a, b)) # same as np.concatenate((a, b), axis=0)
print(c)
print()

d = np.concatenate((a,c,b), axis=0)
#print(d)
#print()

e = np.concatenate((a, b), axis=1)
print(e)

[[ 1  2  3]
 [ 2  3  4]
 [10 11 12]
 [11 12 13]]

[[ 1  2  3 10 11 12]
 [ 2  3  4 11 12 13]]


##### Example

Let's look at the sample [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) again, and re-arrange it so that it first contains samples with the label -1, followed by all samples with the label 1:

In [65]:
samples = np.array([[0.5, 10, 1.7],
                    [0.2, 15, 6.3],
                    [0.7, 17, 5.2],
                    [0.1, 12, 2.8],
                    [0.3, 15, 6.8]])
labels = np.array([-1, -1, 1, 1, -1])

# select only samples where the label is -1
neg = samples[labels == -1]
# and only samples where the label is +1
pos = samples[labels ==  1]

# then, create a rearranged array where the positive samples follow the negative
rearranged = np.concatenate((neg, pos))
print(rearranged)

[[ 0.5 10.   1.7]
 [ 0.2 15.   6.3]
 [ 0.3 15.   6.8]
 [ 0.7 17.   5.2]
 [ 0.1 12.   2.8]]


What if we just want to add a new sample, e.g. $[0.2, 13, 4.1]$ to the list of samples?

We could use for example [`np.vstack()`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html):
> `numpy.vstack((a1, a2, ...))`
>
> Returns an new array with `a1`, `a2`, ... combined along the _vertical_ (first) axis. It will "reshape" 1D arrays of shape (N,) into shape (1, N).

There are many other functions for combining arrays. [`numpy.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate) and [`numpy.stack()`](https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack) are more general, while [`numpy.vstack()`](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html), [`numpy.hstack()`](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack) and [`numpy.dstack()`](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html#numpy.dstack) are for specific use-cases.

##### Example

Let's add a new sample `[0.2, 13, 4.1]` to the above array `samples`:
- using `numpy.vstack()`,
- using `numpy.concatenate()`.

In [66]:
new_sample = np.array([0.2, 13, 4.1])

# with vstack, we can directly add a new row to the array
print(np.vstack((samples, new_sample)))

# concatenate combines two arrays, so we have to nest the sample inside brackets [] :
print(np.concatenate((samples, [new_sample])))

[[ 0.5 10.   1.7]
 [ 0.2 15.   6.3]
 [ 0.7 17.   5.2]
 [ 0.1 12.   2.8]
 [ 0.3 15.   6.8]
 [ 0.2 13.   4.1]]
[[ 0.5 10.   1.7]
 [ 0.2 15.   6.3]
 [ 0.7 17.   5.2]
 [ 0.1 12.   2.8]
 [ 0.3 15.   6.8]
 [ 0.2 13.   4.1]]


## Operations with arrays

[NumPy](https://numpy.org/doc/stable/) provides functionality of operations on [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). This refers to **operations that change the data in the [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)**. 

### Operations between [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) and numbers

[NumPy](https://numpy.org/doc/stable/) supports element-wise addition, subtraction, multiplication and division by a scalar (number).

##### Examples

Let's show some examples on 1D and 2D [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) and compare them to list-comprehension on python lists.

We can see that using performing the same operation on [NumPy](https://numpy.org/doc/stable/) [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) has a much simpler syntax. This is more obvious for more complex examples. Let's show a list of increasingly complex operations between [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), lists and numbers:
- adding a number to all elements of a 1D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) compared to the same operation using list comperhension on a single list:

In [132]:
flist = [0.5, 1.6, 2.7, 3.8, 9.1]
farray = np.array(flist)

flist = [e+2 for e in flist]

farray += 2

print(flist)
print(farray)

[2.5, 3.6, 4.7, 5.8, 11.1]
[ 2.5  3.6  4.7  5.8 11.1]


- adding a number of all elements of a 2D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) is even simpler compared to doing the same with list comperhension for a nested list:

In [133]:
nlist = [[5, 1, 3],
         [2, 7, 1],
         [8, 1, 0]]

narray = np.array(nlist)

narray = narray+5

nlist = [[num+5 for num in line] for line in nlist]

print(narray)
print(nlist)

[[10  6  8]
 [ 7 12  6]
 [13  6  5]]
[[10, 6, 8], [7, 12, 6], [13, 6, 5]]


### Operations between arrays and arrays

With the same syntax, we can perform addition and subraction between [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). As above, as the complexity of our operations increases, the advantage of [NumPy](https://numpy.org/doc/stable/) over basic python lists becomes more clear:

##### Example

Adding two 1D [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of the same length together with [NumPy](https://numpy.org/doc/stable/) and using python list comperhension.

In [67]:
flist = [0.5, 1.6, 2.7, 3.8, 9.1]
farray = np.array(flist)

flist2 = [1.7, 2.1, 10.0, 3.5, 6.2]
farray2 = np.array(flist2)

flsum = [e1 + e2 for e1, e2 in zip(flist, flist2)]
fasum = farray + farray2

print(flsum)
print(fasum)

[2.2, 3.7, 12.7, 7.3, 15.3]
[ 2.2  3.7 12.7  7.3 15.3]


##### Example

We can also do operations between two 2D [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) (matrices) easily in NumPy, where Python list comperhension gets quite complicated.

In [68]:
nlist = [[5, 1, 3],
         [2, 7, 1],
         [8, 1, 0]]

narray = np.array(nlist)
nlist2 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
narray2 = np.array(nlist2)

nlsum = [[n1+n2 for n1, n2 in zip(l1, l2)] for l1, l2 in zip(nlist, nlist2)]
nasum = narray+narray2

print(nlsum)
print(nasum)

[[6, 3, 6], [6, 12, 7], [15, 9, 9]]
[[ 6  3  6]
 [ 6 12  7]
 [15  9  9]]


##### Example

All elements of [NumPy](https://numpy.org/doc/stable/) we have shown so far interact. For example, we can combine operations on [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) together with mask-indexing to produce a more complex mask selection.

In this example, we select all rows from an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) where the sum of the 2nd and 3rd column is higher than 10:

In [71]:
myarray = np.array([[1, 5, 2, 5],
                    [4, 7, 4, 1],
                    [3, 9, 2, 3],
                    [5, 12, 0, 1],
                    [3, 4, 5, 3]])
mask = (myarray[:, 1] + myarray[:, 2]) > 10
print(myarray[mask])
# This can also be done directly in one line as:
#print(myarray[myarray[:, 1]+myarray[:, 2] > 10])

[[ 4  7  4  1]
 [ 3  9  2  3]
 [ 5 12  0  1]]


## Analysing data

So far we have shown binary operations between [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) and numbers (_math: matrices and scalars_), and binary operations on arrays (addition, subtraction, multiplication).

Now, let's showcase some NumPy functionality which is typicaly applied not to whole [_arrays_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), but rather individual **axis** (dimensions) of an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html). These can often help us summarise our data.

We'll start work on a square 5x7 [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of random numbers:

In [72]:
A = np.random.random_sample((4, 6))
print(A)

[[0.93069611 0.2740849  0.81099762 0.7488599  0.1035448  0.12187852]
 [0.79732488 0.59416377 0.27161424 0.31343012 0.52251548 0.72937514]
 [0.3481141  0.290982   0.2460256  0.71982228 0.65326331 0.18355738]
 [0.66245286 0.70495429 0.03185434 0.38100865 0.68634185 0.13236255]]


##### Example

Let us find the maximal value in each row, in each column, and in the whole [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

This can be done with [`numpy.amax()`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) function (and to calculate the minimum, you can similarly use [`numpy.amin()`](https://numpy.org/doc/stable/reference/generated/numpy.amin.html):
> `numpy.amax(a, axis=None)`
>
> `numpy.amin(a, axis=None)`
>
> Returns an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of maximum/minimum values along the axis `axis`. If `axis` is `None`, the maximum of the whole [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) is returned

_Note: This is a simplified function signature._

In [73]:
col_max = np.mean(A, axis = 0)
print(col_max)
row_max = np.mean(A, axis = 1)
print(row_max)
global_max = np.mean(A)
print(global_max)

[0.68464699 0.46604624 0.34012295 0.54078024 0.49141636 0.2917934 ]
[0.49834364 0.5380706  0.40696078 0.43316242]
0.4691343615652044


[NumPy](https://numpy.org/doc/stable/) offers a range of other functions which allow you to summarise the information in different axis. Let's look at some more of them.

To add all numbers per row/column or the whole [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), you can use [`numpy.sum()`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).

The get the mean of all numbers in a row/column/[_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), you can use [`numpy.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html).

_Reminder:_ An (arithmetic) mean of several scalars (denoted by $\mu$ in maths) is calculated by summing them together and then dividing by the total number of scalars, e.g. the mean of $1, 2, 3, 4, 5$:
$$\mu=\frac{1+2+3+4+5}{5} = \frac{15}{5} = 3$$

To get the standard deviation per row/column/[_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html), you can use [`numpy.std()`](https://numpy.org/doc/stable/reference/generated/numpy.std.html).

_Reminder:_ The standard deviation of several scalars is a measure of how "spread out" these scalars are around the mean. This is calculated by shifting all scalars by their mean (to obtain "deviations from the mean"), and taking a square root of the average of *squared* deviations from the mean. If our samples are again $1, 2, 3, 4, 5$, with $\mu=3$, we have for the standard deviation:

$$
\begin{align}
\sigma &= \sqrt{\frac{\sum{(x_i-\mu)^2}}{N}} \\
&= \sqrt{\frac{(1-3)^2+(2-3)^2+(3-3)^2+(4-3)^2+(5-3)^2}{5}} \\
&= \sqrt{\frac{(-2)^2+(-1)^2+0^2+1^2+2^2}{5}} \\
&= \sqrt{\frac{4+1+0+1+4}{5}} \\
&= \sqrt{\frac{10}{5}} \\
&= \sqrt{2} \approx 1.4
\end{align}
$$

##### Example

Of two sets of scalars with the same mean, the one with a bigger standard deviation will be more "spread out":
$$
\mathbf{x} = \{1, 2, 3, 4, 5\}\\
\mu_\mathbf{x} =3, \sigma_\mathbf{x} \approx 1.4
$$

$$
\mathbf{y} = \{-2, 1, 3, 5, 8\}\\
\mu_\mathbf{y} = 3, \sigma_\mathbf{y} \approx 3.4
$$

Use [NumPy](https://numpy.org/doc/stable/) to calculate the mean and standard deviation of two sets: $\{1, 2, 3, 4, 5\}$ and $\{-2, 1, 3, 5, 8\}$.

In [148]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([-2, 1, 3, 5, 8])
print(np.sum(x)/len(x))
print(np.mean(x), np.std(x))
print(np.mean(y), np.std(y))

3.0
3.0 1.4142135623730951
3.0 3.40587727318528


##### Example 

Calculate the mean of every column and row in a 2D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html).

In [156]:
A = np.arange(100).reshape(10,-1)
#.reshape(10, 10)
#print(A)
col_mean = np.mean(A, axis=0)
print(col_mean)
row_mean = np.mean(A, axis=1)
print(row_mean)

[45. 46. 47. 48. 49. 50. 51. 52. 53. 54.]
[ 4.5 14.5 24.5 34.5 44.5 54.5 64.5 74.5 84.5 94.5]


_Note:_ In the above example, we have used [`ndarray.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html) to re-arrange a 1D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) into 2D. It can be used to reshape any [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) into an arbitrary number of dimensions, as long as the number of elements match. This is a **method of the [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) class**, not a separate [NumPy](https://numpy.org/doc/stable/) function:
> `ndarray.reshape(newshape)`
>
> Return a new view of the array with dimensions given by `newshape`.

The opposite of `numpy.reshape` is [`ndarray.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) which can be used to "unroll" an [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) of any shape into a 1D [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html):
> `ndarray.flatten()`
>
> Returns a changed, flattened view of the given [_array_](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

In [44]:
A = np.random.random_sample((5, 5))
print(A.shape)
A = A.flatten()
print(A.shape)

(5, 5)
(25,)


##### Example

Calculating $\pi$ using Gregory–Leibniz series. The value of $\pi$ can be written as the following infinite sum:

$$
\pi=\sum_{i=1}^{\infty}{\frac{(-1)^{i+1}4}{2i-1}}
$$

Let's try and write a [NumPy](https://numpy.org/doc/stable/) function that estimates the value of $\pi$ using the first $n$ terms of the above series.

In [157]:
def estimate_pi(n):
    i = np.arange(1, n+1) # remember, last element not included in arrange
    pi = np.sum((-1)**(i+1)*4 / (2*i-1))
    return pi

print("Six decimal places of pi: {:.6f}".format(np.pi))

print("Six decimal places of G-L series (1 term): {:.6f}".format(estimate_pi(1)))

for i in range(5, 100, 5):
    print("Six decimal places of G-L series ({} terms): {:.6f}".format(i, estimate_pi(i)))
    
for i in range(100, 1000, 100):
    print("Six decimal places of G-L series ({} terms): {:.6f}".format(i, estimate_pi(i)))
    
print("Six decimal places of G-L series (5000 terms): {:.6f}".format(estimate_pi(5000)))

Six decimal places of pi: 3.141593
Six decimal places of G-L series (1 term): 4.000000
Six decimal places of G-L series (5 terms): 3.339683
Six decimal places of G-L series (10 terms): 3.041840
Six decimal places of G-L series (15 terms): 3.208186
Six decimal places of G-L series (20 terms): 3.091624
Six decimal places of G-L series (25 terms): 3.181577
Six decimal places of G-L series (30 terms): 3.108269
Six decimal places of G-L series (35 terms): 3.170158
Six decimal places of G-L series (40 terms): 3.116597
Six decimal places of G-L series (45 terms): 3.163812
Six decimal places of G-L series (50 terms): 3.121595
Six decimal places of G-L series (55 terms): 3.159773
Six decimal places of G-L series (60 terms): 3.124927
Six decimal places of G-L series (65 terms): 3.156976
Six decimal places of G-L series (70 terms): 3.127308
Six decimal places of G-L series (75 terms): 3.154925
Six decimal places of G-L series (80 terms): 3.129093
Six decimal places of G-L series (85 terms): 3.153

## Basic linear algebra (extension)

NumPy stands for Numerical Python -- and is very useful for performing mathematical operations with matrices. The above example (addition of two matrices) is a basic example of that. Let's go through some more complicated matrix operations.

Let's first introduce matrices as used in maths, and (mathematically) define some basic operations with them:

$$
M=
\begin{bmatrix}
5 & 3 & 1 \\
2 & 4 & 6
\end{bmatrix}
$$

$$
N=
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

Both M and N define two-dimensional (2D) matrices. The matrix $M$ has dimensions $2\times3$ (in general, $\texttt{rows} \times \texttt{columns}$). The matrix $N$ has dimensions $2x2$; we can also call it a _square_ matrix of dimension 2.

In [36]:
M = np.array([[5, 3, 1],
              [2, 4, 6]])
N = np.array([[1, 2],
              [3, 4]])
print(M.shape)
print(N.shape)

(2, 3)
(2, 2)


If either the number of rows or the number of columns is $1$, we talk about **vectors** instead. Vectors are usually denoted by lower case letters.

A **column-vector** has only 1 column, and several rows (effectively, it is a matrix of dimensions $(n\times1)$. For example, a column-vector of length 4:
$$
v_1 =
\begin{bmatrix}
5 \\
4 \\
8 \\
1
\end{bmatrix}
$$

A **row-vector** has only 1 row, and several columns (effectively, it is a matrix of dimensions $(1\times n)$. For example, a row-vector of length 5:
$$
v_2 =
\begin{bmatrix}
4 & 2 & 1 & 9 & 3
\end{bmatrix}
$$

In [37]:
v1 = np.array([[5],
               [4],
               [8],
               [1]])
v2 = np.array([[4, 2, 1, 9, 3]])
print(v1.shape)
print(v2.shape)

(4, 1)
(1, 5)


_Note:_ When working with vectors in NumPy, the dimension of size $1$ is often avoided all together (initialising from a non-nested list):

In [38]:
v1d = np.array([5, 10, 15, 20])
print(v1d)
print(v1d.shape)

[ 5 10 15 20]
(4,)


**Transposing** a matrix means swapping it's rows and columns. So if a matrix $M$ has dimensions $(m\times n)$, the transposed matrix $M^\top$ will have dimensions $(n \times m)$:
$$
M=
\begin{bmatrix}
5 & 3 & 1 \\
2 & 4 & 6
\end{bmatrix} \\
M^\top=
\begin{bmatrix}
5 & 2 \\
3 & 4 \\
1 & 6
\end{bmatrix} \\
$$

This can be done with the NumPy function [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html):
> `numpy.transpose(a)`
>
> Returns a transpose of the matrix `a`

_Note: This is a simplified function signature._

In [39]:
print(M)
print(np.transpose(M))

[[5 3 1]
 [2 4 6]]
[[5 2]
 [3 4]
 [1 6]]


Transposing a column-vector results in a row-vector, and the other way around. It is common to write column-vectors as transposed row-vectors:
$$
v_1 =
\begin{bmatrix}
5 \\
4 \\
8 \\
1
\end{bmatrix} = 
\begin{bmatrix}
5 & 4 & 8 & 1
\end{bmatrix}^\top
$$

This gives us another way to define column-vectors in NumPy:

In [40]:
v1again = np.transpose(np.array([[5, 4, 8, 1]]))
print(v1again)
print(v1again.shape)

[[5]
 [4]
 [8]
 [1]]
(4, 1)


We can only **add and subtract** matrices of the same dimensions. This is done element-wise. For example, addition of square matrices:
$$
A=
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
B=
\begin{bmatrix}
9 & 7 \\
8 & 6
\end{bmatrix}
\\
A + B = 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}+
\begin{bmatrix}
9 & 7 \\
8 & 6
\end{bmatrix}=
\begin{bmatrix}
1+9 & 2+7 \\
8+3 & 6+4
\end{bmatrix}=
\begin{bmatrix}
10 & 9 \\
11 & 10
\end{bmatrix}
$$

In [41]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[9, 7],
              [8, 6]])
print(A+B)

[[10  9]
 [11 10]]


Or, subtraction of non-square matrices:
$$
C=
\begin{bmatrix}
10 & 15 \\
5 & 25 \\
30 & 20
\end{bmatrix},
D=
\begin{bmatrix}
2 & 3 \\
4 & 5 \\
6 & 7
\end{bmatrix}
\\
C - D = 
\begin{bmatrix}
10 & 15 \\
5 & 25 \\
30 & 20
\end{bmatrix}-
\begin{bmatrix}
2 & 3 \\
4 & 5 \\
6 & 7
\end{bmatrix}=
\begin{bmatrix}
10-2 & 15-3 \\
5-4 & 25-5 \\
30-6 & 20-7
\end{bmatrix}=
\begin{bmatrix}
8 & 12 \\
1 & 20 \\
24 & 13
\end{bmatrix}
$$

In [42]:
C = np.array([[10, 15],
              [5, 25],
              [30, 20]])
D = np.array([[2, 3],
              [4, 5],
              [6, 7]])
print(C-D)

[[ 8 12]
 [ 1 20]
 [24 13]]


Matrices can also be **multiplied**, but only when they have dimensions $(\texttt{rows}_1 \times \texttt{columns}_1$), $(\texttt{rows}_2 \times \texttt{columns}_2)$, such that $\texttt{columns}_1 = \texttt{rows}_2$. The resulting matrix dimensions are $(\texttt{rows}_1 \times \texttt{columns}_2)$

This is done like so:
$$
\begin{align}
\begin{bmatrix}
1 & 2 & 4 \\
7 & 5 & 3
\end{bmatrix}\times
\begin{bmatrix}
2 & 3 \\
4 & 5 \\
6 & 7
\end{bmatrix}=&\\
&\begin{bmatrix}
\phantom{-2\times1 + 4\times2 + 6\times}2 & \phantom{3\times1 + 5\times2 + 7\times}3 \\
\phantom{-2\times1 + 4\times2 + 6\times}4 & \phantom{3\times1 + 5\times2 + 7\times}5 \\
\phantom{-2\times1 + 4\times2 + 6\times}6 & \phantom{3\times1 + 5\times2 + 7\times}7
\end{bmatrix} \\
\begin{bmatrix}
1 & 2 & 4 \\
7 & 5 & 3
\end{bmatrix}
&\begin{bmatrix}
2\times1 + 4\times2 + 6\times4 & 3\times1 + 5\times2 + 7\times4 \\
2\times7 + 4\times5 + 6\times3 & 3\times7 + 5\times5 + 7\times3
\end{bmatrix} \\
=&\begin{bmatrix}
\phantom{2\times1 + 4\times2 + 6\times}34 & \phantom{3\times1 + 5\times2 + 7\times}41 \\
\phantom{2\times1 + 4\times2 + 6\times}52 & \phantom{3\times1 + 5\times2 + 7\times}67
\end{bmatrix}
\end{align}
$$

In Numpy, we can use the function [`numpy.matmul`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) to perform matrix multiplication:
> `numpy.matmul(x1, x2)`
> 
> Returns the result of multiplication between matrices or vectors `x1` and `x2`. Scalars (numbers) not allowed.

_Note: This is a simplified function signature._

In [43]:
X = np.array([[1, 2, 4], 
              [7, 5, 3]])
Y = np.array([[2, 3],
              [4, 5], 
              [6, 7]])
A = np.matmul(X, Y)
print(A)

[[34 41]
 [52 67]]


If we multiply any matrix $A$ with a **diagonal matrix** containing the value $1$ on the diagonals and $0$ otherwise (called the **identity** matrix $I$), the original matrix $A$ does not change (like multipying scalars by $1$):
    
$$
A I = I A = A \\
\begin{bmatrix}
34 & 41 \\
52 & 67
\end{bmatrix} \times
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix} =
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix} \times
\begin{bmatrix}
34 & 41 \\
52 & 67
\end{bmatrix}
= \begin{bmatrix}
34 & 41 \\
52 & 67
\end{bmatrix}
$$
    
This also works for non-square matrices (take care of matrix dimensions!):
$$
\begin{bmatrix}
1 & 2 & 4 \\
7 & 5 & 3
\end{bmatrix} \times
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix} = 
\begin{bmatrix}
1 & 2 & 4 \\
7 & 5 & 3
\end{bmatrix}
$$
    
You can initialise identity matrix in NumPy with [`numpy.eye`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye):
> `numpy.eye(rows, [columns])`
>
> Returns an identity matrix with dimensions (`rows`$\times$`columns`). By default, number of columns is equal to the number of rows, and a square identity matrix is created.

_Note: This is a simplified function signature._

In [44]:
I2by2 = np.eye(2)
I3by3 = np.eye(3)
I4by2 = np.eye(4, 2)

print("Identity matrices:")
print(I2by2)
print(I3by3)
print(I4by2)

print("Compare A to AI:")
print(np.array_equal(A, np.matmul(A, I2by2)))

print("Compare X to XI (non-square):")
print(np.array_equal(X, np.matmul(X,I3by3)))


Identity matrices:
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]
Compare A to AI:
True
Compare X to XI (non-square):
True


To compare the two matrices (the matrix $A$ with the result of multiplying $A$ and identity), we used [`numpy.array_equal`](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html):
> `numpy.array_equal(a1, a2)`
>
> Returns `True` if the arrays are equal.

_Note: This is a simplified function signature._

It is **not possible to divide** two matrices. Instead, we can **multipy by the inverse**.

An **inverse** is a matrix $A^{-1}$ which, when multiplied with $A$, results in the identity matrix $I$. (We will not show the formula to calculate it, but you can check that the following holds:)
    
$$
A=
\begin{bmatrix}
10 & 4 \\
2 & 1
\end{bmatrix},
A^{-1} = 
\begin{bmatrix}
0.5 & -2 \\
-1 & 5
\end{bmatrix}
\\
A \times A^{-1} = 
\begin{bmatrix}
10 & 4 \\
2 & 1
\end{bmatrix}\times
\begin{bmatrix}
0.5 & -2 \\
-1 & 5
\end{bmatrix}=
\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix} = I
$$

_Note:_ Some matrices don't have an inverse.

To calculate an inverse in NumPy, we can use [`numpy.linalg.inv`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html):
> `linalg.inv(a)`
>
> Returns an inverse of matrix `a` if `a` is square and has an inverse.

_Note: This is a simplified function signature._

In [45]:
A = np.array([[10, 4],
              [2, 1]])
Ainv = np.linalg.inv(A)
print(Ainv)

print("Check multiplying with inverse gives identity:")
print(np.array_equal(np.eye(2), np.matmul(A, Ainv)))
print(np.array_equal(np.eye(2), np.matmul(Ainv, A)))

[[ 0.5 -2. ]
 [-1.   5. ]]
Check multiplying with inverse gives identity:
True
True


When working in matrices, there is a distinction between multiplying by some matrix **from the left** or **from the right**. So, while it is always true that multiplying a matrix with it's inverse (from left or right) gives identity:
$$
A \times A^{-1} = A^{-1} \times A = I
$$

Order can not be swapped when multiplying any two matrices in general:
$$
X \times Y \neq Y \times X
$$

In fact, often, only one of the products is defined. If $X$ has dimensions $(n, k)$ and $Y$ has dimensions $(k, m)$, it is always possible to calculate $X\times Y$. However, $Y\times X$ only exists if $n=m$.

### System of linear equations (extension)

In general, if we have a system of $n$ unknowns, or variables, we need $n$ equations to attempt to solve them. If all the unknowns are linear (so, no squared values) in all the equations, this is called a **system of linear equations:**

$$
3 x_1 +   x_2 - 2 x_3 = -3 \\
- x_1 + 2 x_2 + x_3 = 0  \\
2 x_1 - 2 x_2 - x_3 = 2  \\
$$

We can write this in matrix form:

$$
\begin{bmatrix}
3 & 1 & -2 \\
-1 & 2 & 1 \\
2 & -2 & -1
\end{bmatrix} \times
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix} =
\begin{bmatrix}
-3 \\
0 \\
2
\end{bmatrix}
$$

Now, if we substitute:
$$
A = \begin{bmatrix}
3 & 1 & -2 \\
-1 & 2 & 1 \\
2 & -2 & -1
\end{bmatrix},
X = \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix},
B = \begin{bmatrix}
-3 \\
0 \\
2
\end{bmatrix}
$$

We can get:
$$
A X = B \\
A^{-1} A X = A^{-1} B \\
X = A ^{-1} B
$$

Now, if we know that:
$$
A^{-1} = 
\begin{bmatrix}
0 & 1 & 1 \\
\frac{1}{5} & \frac{1}{5} & -\frac{1}{5} \\
-\frac{2}{5} & \frac{8}{5} & \frac{7}{8}
\end{bmatrix}
$$

We can calculate:
$$
\begin{align}
X &= A ^{-1} B \\
X &= 
\begin{bmatrix}
0 & 1 & 1 \\
\frac{1}{5} & \frac{1}{5} & -\frac{1}{5} \\
-\frac{2}{5} & \frac{8}{5} & \frac{7}{8}
\end{bmatrix} \times
\begin{bmatrix}
-3 \\
0 \\
2
\end{bmatrix} \\
X &= \begin{bmatrix}
2 \\
-1 \\
4
\end{bmatrix} \\
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix} &= \begin{bmatrix}
2 \\
-1 \\
4
\end{bmatrix} \\
x_1 = 2, x_2 &= -1, x_3 = 4
\end{align}
$$

In [46]:
A = np.array([[3, 1, -2],
              [-1, 2, 1],
              [2, -2, -1]])

B = np.array([-3, 0, 2])
B = np.transpose(B)

X = np.matmul(np.linalg.inv(A), B)

print(X)

[ 2. -1.  4.]


We can also check that using these values satisfy the given system of linear equations:

$$
A X = B \\
A = \begin{bmatrix}
3 & 1 & -2 \\
-1 & 2 & 1 \\
2 & -2 & -1
\end{bmatrix},
X = \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}=
\begin{bmatrix}
2 \\
-1 \\
4
\end{bmatrix}
$$
<br><br>
$$
\begin{align}
A X &= \begin{bmatrix}
3 & 1 & -2 \\
-1 & 2 & 1 \\
2 & -2 & -1
\end{bmatrix}
\begin{bmatrix}
2 \\
-1 \\
4
\end{bmatrix} \\
&= \begin{bmatrix}
3\times2 & 1\times(-1) & -2\times4 \\
-1\times2 & 2\times(-1) & 1\times4 \\
2\times2 & -2\times(-1) & -1\times4
\end{bmatrix} \\ 
&= \begin{bmatrix}
6-1-8 \\
-2-2+4 \\
4+2-4
\end{bmatrix}\\
&= \begin{bmatrix}
-3 \\
0 \\
2
\end{bmatrix} \\
&= B
\end{align}
$$


In [47]:
print(np.matmul(A, X))

[-3.  0.  2.]
